### ISSUE TITLE
IE9/IE10: Text editor boxes not initially clickable

### ISSUE THREAD

**Issue by lenglund** [ubc/compair#205]
Similar to the issue noticed a few times with Chrome, a user can't always click in and edit answers, write comparisons, etc. when using the text editor. Refreshing the page fixes this, as does clicking something in the editor toolbar.

**Comment by mwytang** [comment]
I have attempted to find the issue behind this problem. I was able to reproduce the problem pretty consistently (eg. 2 to 3 out of 5 times for IE 9/10).

I have discovered:
- The text area is technically contenteditable (eg. not readOnly)
- a TypeError tend to appear on the console whether the ckeditor works or not
- when I changed the configuration to have 'startupFocus' to be true, it seems to have fixed the problem. However for screens that have multiple ckeditors (eg. evaluation screen), it is random which ckeditor the cursor will be at

I will come back to this at another time, since I was unable to make any more progress. As a "workaround" I suggest putting a note near the ckeditors to let the users know they can "fix" the problem by clicking one of the tools in the toolbar. By doing so, they will not have to refresh the page. Refreshing the page is an option for submitting answers but not so much for evaluations because they will have to redo the whole form.

**Comment by lenglund** [comment]
I like the approach of using inline. Progressively revealing the toolbar is fine, I think, unless there is a use case this would not work for?

**Comment by mwytang** [comment]
Tested with ckeditor directly. Have found the same problem when using `replace`.

**Comment by ionparticle** [comment]
To make it even more confusing, I've failed to reproduce this on my Win7/IE9 and Win8.1/IE11 VMs.  

I've tried these approaches at least 10 times each:
- Refreshing
- Back and Forward
- Clicking on the course name > Add Question

Each time, the javascript console shows no errors. This is weird because I've seen @mwytang reproduce this and seen the errors. Is there a hardware factor to this as well?!

**Comment by ionparticle** [comment]
I can now reproduce this by going to a question > Help > Comment. But no javascript errors occur. It seems more like IE gets stuck on a request that wasn't completed or something.

**Comment by lenglund** [comment]
Yeah, I found that if the error is going to happen, it will only happen the first time you load a new form with the ckeditor in it.

**Comment by lenglund** [comment]
Closing unless anyone has a solution for resolution. We can re-open if this becomes an issue for users.
