### ISSUE TITLE
Instructor or TA generated pairs

### ISSUE THREAD

**Issue by xcompass** [ubc/compair#248]
This is propose by James: 

> I was talked about ACJ with the physics education group and the idea came up that it would be neat if instructors and TAs could generate a comparison list as well to use as a control. This would be accomplished though some combination of having the instructor do more comparisons and for large classes only sampling a subset of the entire course.

**Comment by lenglund** [comment]
Can we consider this issue closed now that we've added the instructor/TA option to compare? It seems perhaps unrealistic to me that the instructors/TAs would want to do enough pairs to compare against the student rankings (assuming they would need to go through as many rounds as the students do in order to generate a fair comparison).

**Comment by andrew-gardener** [comment]
Instructors and TAs can now compare as many answers as they want by enabling it in the assignment. This should allow instructors or TAs to calibrate as much as they are willing to do
