### ISSUE TITLE
Random pairing still displays answer score

### ISSUE THREAD

**Issue by lenglund** [ubc/compair#412]
Questions with random pairing selected still show answer scores in the participation tab. This should be consistent with the display of answers elsewhere in that the scores are not shown when the pairings are random.

**Comment by lenglund** [comment]
Also would be curious to know how this score is being generated, i.e., what does it mean in the context of random pairing?

**Comment by andrew-gardener** [comment]
It would still give some estimate of how correct an answer is, It just isn't as fair an estimate as its possible for for a wider variety of unhelpful pairings (ex: several average answers gets top ranks since they are only randomly paired with bad answers which they always win).

The way I have random pairing setup still tries to have all answers compared an equal amount of times so all answers should get compared.
