### ISSUE TITLE
Handle deleted LTI courses/assignments

### ISSUE THREAD

**Issue by lenglund** [ubc/compair#485]
When you delete a course that is linked with LTI, the error message is not user-friendly when you use the course link to access the deleted course.

Instead redirect the user to the home page with a better error message

**Comment by andrew-gardener** [comment]
linked to #554

**Comment by andrew-gardener** [comment]
Just dealt with an issues brought up in INC0894282 around lti linked courses

The user deleted an LTI linked ComPAIR course. They then received the "course is no longer available" message when trying to follow link. They then tried to create another link and got the same message. It seems that the expected behavior would be to be able to recover from this in some way instead of being locked out.

Maybe instead of just displaying a message for deleted courses we should do a bit more work and:
1) unlink lti contexts and resource links when deleting ComPAIR courses/assignments
2) re-activate deleted courses/assignments when someone follows an LTI link that is linked to a deleted course/assignment
3) or do what was originally planned and just display message

**Comment by lenglund** [comment]
Not sure if I'm reading this correctly, but I would advocate for better prevention of deleting in the first place. Do we let instructors/admins know when they are deleting a course that has been linked via LTI and what the consequences will be (i.e., this will break links from any external sources)? IOW, we should probably handle linked course deletion differently than non-linked course deletion. I don't know that we can or should assume a user wants to re-activate a link because they clicked on it (i.e., maybe they are confirming it no longer works).

**Comment by lenglund** [comment]
Implement #1 and improve error message when a linked course is being deleted.
