### ISSUE TITLE
Implement image uploader that allows for manipulating orientation

### ISSUE THREAD

**Issue by lenglund** [ubc/compair#607]
An instructor notes:

> I'm having my students upload pictures of their written homework (it's 
> math, they need to write a lot of equations so hand writing is faster) but 
> I noticed that many upload images with a landscape orientation, which will 
> make the comparison hard (you sort have to tilt the screen to be able to 
> read it). is there a way in ComPAIR to change orientation of a document?

**Comment by lenglund** [comment]
Mentioned by another instructor in grading/analytics interview. This presents a significant challenge to students who are less tech-savvy, as they are trying to read one or more answers in the pair sideways. We should definitely enable students to correct this.

**Comment by wynnset** [comment]
Here's what we need to do for this:
- Update the answer screen:
  - When the student chooses a file to upload, immediately upload the file to a temporary location, and display a preview of their image to them, along with rotate controls (rotate clockwise / counterclockwise). Note that the student can only upload 1 image, so we don't need support for multiple images.
  - Allow the student to rotate their image, whether it's in a temporary location or permanently saved. 
  - When the student presses the button for rotate image, immediately send a request to the server to rotate the image, store it in a temporary location, and display the updated (rotated) image to them.
  - The student must press the "Save" button to save their rotation. Otherwise, if the image was never uploaded, it should not show up, or if it was uploaded before, it should be displayed in its original orientation. (i.e. always save to a temporary location when rotating, and only move the file to a permanent location and update the answer with its new location if they press "Save")
- Create a scheduled task to clean up the temporary folder. Ensure that this doesn't remove images if the student is currently in the process of uploading / rotating their image.

**Comment by wynnset** [comment]
@lenglund does my comment above make sense? If we allow the uploader to view and rotate their image, then it will appear correctly for all students vs. adding the controls in the compare screen, which means all students will have to rotate it. We could potentially add both options.

**Comment by lenglund** [comment]
Sounds good to me. Let's start with enabling the author to rotate and see if that's enough to solve the problem.

**Comment by andrew-gardener** [comment]
If possible I'd prefer that images can only be rotated in preview (before upload handled by js without backend) and if they need to be rotated again, the user removes the current attachment and uploads it again with desired orientation.

Reason being that 
1) reduces the back-end complexity
2) reduces potential future problems with LA recording (since orientation changes would affect sha fingerprints)

**Comment by kitsook** [comment]
@wynnset Just a thought.  Would it be easier to defer the upload and preview / rotate the image using Javascript?  When the user decided to upload, include the degree to rotate in the API call and apply the rotation to the image when saving.

**Comment by xcompass** [comment]
will do the rotation in the frontend and save the rotated image to the backend.
