### ISSUE TITLE
Add student view option

### ISSUE THREAD

**Issue by lenglund** [ubc/compair#628]
James explains:

> The purpose of it would be so professors can answer [student] questions like "Can I edit my assignment after I submit it? How?" The professor can then go to student view, submit a test assignment to a question that they've created, then try to edit it. When they exit, it wipes the test environment. It might be enough to add one more case to the demo site for students that doesn't immediately go to a comparison phase. But, it would be better if the prof could see what the students see when they go to their course. 
> 
> In many cases these are sort of a sanity check for the prof. It makes them sure that the students are seeing what the profs wants them to see as they move through the course.

**Comment by andrew-gardener** [comment]
Both Connect and Canvas have student views which can create new student accounts in ComPAIR (will require #606 so student account doesn't require CWL login though).

**Comment by lenglund** [comment]
Ideal would be to let the instructor act as a student enrolled in the course. But we don't want to save any data permanently (no answers in the answer pool or visible later, no comparisons affecting the scores or visible later).

**Comment by xcompass** [comment]
first attempt: impersonation with read-only view and a message

**Comment by kitsook** [comment]
Changes needed:
- [ ] mechanism to control who can impersonate who (e.g. a professor can impersonate a student in his course; only students can be impersonated etc)
- [ ] mechanism to control which course can be accessed while impersonating (e.g. courses the original user has access to)
- [ ] read-only access during impersonation.  Only allow GET requests.  All POST / PUT requests will be denied
- [ ] visual cue to indicate the user is impersonating who and ability to exit impersonation

Initial idea:
- no changes to existing API / logic. See if possible to implement it as a Flask extension
- add a filter to intercept all incoming requests with `@app.before_request`.  If login user is impersonating another user and all criteria checked OK, switch the `current_user` to the one being impersonated and allow the request to continue.  Otherwise return error.
- modify callbacks of `flask-login` and `flask-bouncer` (and functions in `authorization`) to allow impersonation
- add visual cue when impersonating.  Inject via `after_request` or `teardown_request`
