### ISSUE TITLE
Students allowed to complete more than assigned number of comparisons

### ISSUE THREAD

**Issue by wynnset** [ubc/compair#658]
This is a bug that needs to be fixed.

If I log in as a student and complete 3/3 comparisons, the application rightly takes me to self-eval screen. At this point, if I click the back button and go to the previous screen (compare), I'm asked to complete another comparison. The "Round" indicator at the top would say "Round 4/4", so it even appears as if the user should complete this.

The same thing happens if I enter the URL for compare directly into the browser.

Self-eval screen can also be accessed after it has been done. This might be related, but needs to be fixed as well, regardless.

We need to put in a fix to return an error message if: 
- the user has already completed their maximum number of comparisons and trying to access the compare screen.
- the user has already self-evaluated and trying to access the self-eval screen

We also need to update the API to not return these things in the first place.

**Comment by andrew-gardener** [comment]
Items to Fix:
- [ ] If I log in as a student and complete 3/3 comparisons, the application rightly takes me to self-eval screen. At this point, if I click the back button and go to the previous screen (compare), I'm asked to complete another comparison. The "Round" indicator at the top would say "Round 4/4", so it even appears as if the user should complete this. 
The same thing happens if I enter the URL for compare directly into the browser. (#659)
- [ ] If I visit the compare page when not allowed, the error message shows up correctly, but in the body of the page, it still says "Break time! You've compared the currently available answer pairs. Please check back later to compare new pairs after more answers have been submitted."
- [ ] User also still seems to be able to access the self-evaluation page for an assignment (and submit) more than one time.
