### ISSUE TITLE
Save draft twice and attachment appears to be lost

### ISSUE THREAD

**Issue by kitsook** [ubc/compair#678]
Steps to reproduce the issue:
- create a new answer
- choose a file as attachment
- click "Save Draft".  The file is shown as attached
- click "Save Draft" again.  The screen shows "No file chosen" and user can choose another file to attach.  But in fact the file is still linked to the answer.  Can be verified by reloading the page.

Seems that AngularJS is not reloading the controller when user clicked on "Save Draft" if the current page is already at `/answer/{answer_id}/edit`.

One way to fake a reload is to append a `/` after `edit` at
https://github.com/ubc/compair/blob/966729f2db4041d04efa8d64f88c1529d7cf78f5/compair/static/modules/answer/answer-module.js#L260

Any other suggestion?

**Comment by kitsook** [comment]
According to the [doc](https://docs.angularjs.org/guide/$location#page-reload-navigation), seems it is the expected behavior for `$location.path` not reloading the page.  Besides appending `/` at the end as a hack, an alternative will be using `$route.reload()`

**Comment by andrew-gardener** [comment]
Adding a `/` isn't a good practice since it will do two $routeChange events (one to go to the url with the `/` and one redirecting to the url without the `/`

It would be better to rather check the current url and do a `$route.reload()` if already on the url or change the save draft action to not require a url reload when saving a draft on the edit screen
