### ISSUE TITLE
Try to prevent students from seeing the same answer again

### ISSUE THREAD

**Issue by lenglund** [ubc/compair#683]
Instructors are grading students on completing a set number of comparisons and this means writing a set amount of feedback. When some students see the same answer(s) again, they end up doing less work than other students; this is both unfair and makes grading a headache (i.e., instructors need to change formulas to account for the different number of peer reviews done).

What can we do to prevent this from happening? How much would that affect scoring?

**Comment by andrew-gardener** [comment]
This can be prevented in the selection algorithm. We are already preventing students from seeing the same pair again so there is already logic in place to remove certain answer pairs from potential comparison pool. We'd just need to remove previously seen answers from the pool entirely.

This shouldn't have any adverse effect on scoring assuming there are a decent amount of answers in the pool. We'd need to update some comparison button conditionals to make sure (assignment comparison requirement * 2 answers are available).

The only really tricky part is that we'd not want this to effect instructor/teaching assistant comparisons since they should still be able to do the full n(n-1)/2 comparisons

Another consideration is that if instuctors would want this as an assignment option? I don't think they would but not sure?

**Comment by lenglund** [comment]
This doesn't need to be an instructor option, since no one wants this be happening (at least not that I know of).
