### ISSUE TITLE
Improve automated testing of workflows

### ISSUE THREAD

**Issue by lenglund** [ubc/compair#714]
Instructors have commented on there being more bugs recently. Can we improve the automated testing of the core workflows to try to better prevent these from making it into production? Pan suggests using a meeting time to go through the tests and brainstorm where we can make improvements.

**Comment by andrew-gardener** [comment]
Having fuller + more stable front-end tests would go a long way. 

I was looking into [selenoid](https://github.com/aerokube/selenoid) as a way to make the acceptance tests run more consistently (we could potentially stop using saucelabs which is very inconsistent).

Otherwise we just need to set aside a fair amount of time to expand the tests

**Comment by lenglund** [comment]
Recommendations:
- [ ] Update existing front-end and integration tests so they are working with the current UI
- [ ] Add new integration tests to fully cover the common workflows
- [ ] Look into alternatives to / issues with saucelabs
- [ ] Create manual testing script for use temporarily (for 1.2 at least)
- Engage LT Hub in QA testing prior to releases

Focus on integration tests more heavily for issue 1.3.
