### ISSUE TITLE
Update background tasks section in README  

### ISSUE THREAD

**Issue by andrew-gardener** [ubc/compair#864]
Background tasks are no longer optional. At the very least `CELERY_ALWAYS_EAGER=1` must be set (or else setting passwords during csv import will not work)

- consider making CELERY_ALWAYS_EAGER `1` by default
- add additional instructions explaining that you need to either have `CELERY_ALWAYS_EAGER=1` or setup redis + worker (+ scheduler in the future). Might be good to also list what kinds of things are done in the background (passwords, lti grade sync, etc)

getting this into master sooner than later would be good

**Comment by kitsook** [comment]
Need to check if the settings of `backend` and `broker` are swapped.

https://github.com/ubc/compair/blob/d849b4768943d4adbec88c732dc721d8345560a0/compair/core.py#L34-L38

**Comment by andrew-gardener** [comment]
Looks like a goofed the settings up. It probably worked since `CELERY_RESULT_BACKEND` is always unset for the broker (so maybe it uses the backend instead is such a case)

**Comment by kitsook** [comment]
@andrew-gardener thanks.  Will include this in the change.  Actually I was tracing the code since the Celery setting is a bit strange.

According to [the doc](http://docs.celeryproject.org/en/latest/userguide/configuration.html#new-lowercase-settings), Celery 4.x changed to use `CELERY_TASK_ALWAYS_EAGER` instead of `CELERY_ALWAYS_EAGER` in the old version.  However, I found that `CELERY_TASK_ALWAYS_EAGER` is ignored by Celery in ComPAIR setup. It only references `CELERY_ALWAYS_EAGER`.

Interestingly, trying to use the new lowercase variable `task_always_eager` will generate this error:
```
Cannot mix new setting names with old setting names, please
rename the following settings to use the old format:

task_always_eager                    -> CELERY_ALWAYS_EAGER

Or change all of the settings to use the new format :)
```

So I guess since we have some other settings in old format, Celery decided to use old format for all variables.  Will document this is README too.
