### ISSUE TITLE
Content of answers after inclusion of emoji is silently discarded

### ISSUE THREAD

**Issue by lf-** [ubc/compair#908]
Reproduced version: whatever the live ComPAIR version is at https://compair.elearning.ubc.ca as of today.

To reproduce:
Enter the following into an answer and press save:

> I acknowledge this is a very strange issue to be reporting in ComPAIR, but 👀👀👀
> 
> On a more serious note, this half of my answer is missing!!

The second paragraph will be missing once submitted and shown back to the user. This is highly unexpected and could result in accidentally losing half of one's answer if trying to be cheeky.

This happened on Chrome 78 on Windows 10.

I poked around in the developer tools network inspector and it appears that the emoji does survive the trip through the client side, and this behaviour is *probably* happening on the server.

Thanks!

**Comment by kitsook** [comment]
The problem is caused by the mysql database setup to use the legacy 3-byte `utf8` character set instead of the proper 4-byte version `utf8mb4`.

Given the nature of the change required, I would suggest to include this in the next version release instead of a hotfix.

To fix this, we need to:
(1) change charset encoding of affected database columns and tables, e.g. for answers:
```
ALTER TABLE answer MODIFY content text charset utf8mb4;
ALTER TABLE answer CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
```

Similar changes needed for other places that wanted to support true unicode e.g. course name/description, assignment name/description, comments etc

(2) The database connection needs to be specify the charset by adding `query={'charset': 'utf8mb4'},` to the connection url.  Probably should setup a default and allow overriding with env variables.
https://github.com/ubc/compair/blob/66de1b2ece10eed19716d56977be28f9b38b5081/compair/configuration.py#L47-L54

**Comment by lenglund** [comment]
Thanks for investigating. Will move to next version.
