### ISSUE TITLE
Comparisons tab should show all students

### ISSUE THREAD

**Issue by lenglund** [ubc/compair#940]
Comparisons tab should show instructors outcomes for all students, not just those with paired comparisons completed.

> I have a corner case of a student who submitted and assignment, didn't complete the comparisons, but completed the self reflection. 
> 
> When I click on "All Comparisons" to look at her work, neither her submission or her self-reflection appear. Because of this, I missed grading some of her work. 
> 
> It would make sense that when "All Comparisons" where clicked it showed the student work and any self reflection they had. If they had none, it would just show their name. If they had only the submission, it would just show the little show student answer arrow.

In the case of no comparisons, we also need to report this, e.g., "No comparisons completed by this student."

**Comment by kitsook** [comment]
Just noticed another issue on the same `All Comparisons` tab.  Self-evaluations on deleted answers will be listed but not counted in the total shown in `All Comparisons (xx)` header.

**Comment by kitsook** [comment]
By similar logic, should we also show all students under the `All Answers` tab too?

If the purpose of these tabs is to show what students have submitted, it seems odd to show empty result.  Also, would it be easier for the instructor to use the "Participation" tab to check the student progress?

Maybe instead of including all users, we just change the "All Comparisons" tab to include users that have completed at least one comparison **or** completed the self-eval?

**Comment by lenglund** [comment]
> Maybe instead of including all users, we just change the "All Comparisons" tab to include users that have completed at least one comparison or completed the self-eval?

Yes, sounds like a better route.
